/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create-post` | `/create-post`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/components/MapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/components/MapComponent.styles`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CreatePost`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Home`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/pages/screens/AdminHome`; params?: Router.UnknownInputParams; } | { pathname: `/pages/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/pages/screens/NormalUserHome`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create-post` | `/create-post`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MapComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MapComponent.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/CreatePost`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/screens/AdminHome`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/screens/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/screens/NormalUserHome`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create-post${`?${string}` | `#${string}` | ''}` | `/create-post${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/components/MapComponent${`?${string}` | `#${string}` | ''}` | `/components/MapComponent.styles${`?${string}` | `#${string}` | ''}` | `/pages/CreatePost${`?${string}` | `#${string}` | ''}` | `/pages/Home${`?${string}` | `#${string}` | ''}` | `/pages/Profile${`?${string}` | `#${string}` | ''}` | `/pages/screens/AdminHome${`?${string}` | `#${string}` | ''}` | `/pages/screens/Home${`?${string}` | `#${string}` | ''}` | `/pages/screens/NormalUserHome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create-post` | `/create-post`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/components/MapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/components/MapComponent.styles`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CreatePost`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Home`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/pages/screens/AdminHome`; params?: Router.UnknownInputParams; } | { pathname: `/pages/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/pages/screens/NormalUserHome`; params?: Router.UnknownInputParams; };
    }
  }
}
